const colors = {
  light: {
    text: '#FFFFFF',
    tint: '#6C5CE7',
    background: '#0d0d1a',
    foreground: '#FFFFFF',
    card: '#1a1a2e',
    cardForeground: '#FFFFFF',
    primary: '#6C5CE7',
    primaryForeground: '#FFFFFF',
    secondary: '#252545',
    secondaryForeground: '#FFFFFF',
    muted: '#252545',
    mutedForeground: '#606080',
    accent: '#4ECDC4',
    accentForeground: '#FFFFFF',
    destructive: '#FF6B6B',
    destructiveForeground: '#FFFFFF',
    border: '#252545',
    input: '#252545',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#6C5CE7',
    background: '#0d0d1a',
    foreground: '#FFFFFF',
    card: '#1a1a2e',
    cardForeground: '#FFFFFF',
    primary: '#6C5CE7',
    primaryForeground: '#FFFFFF',
    secondary: '#252545',
    secondaryForeground: '#FFFFFF',
    muted: '#252545',
    mutedForeground: '#606080',
    accent: '#4ECDC4',
    accentForeground: '#FFFFFF',
    destructive: '#FF6B6B',
    destructiveForeground: '#FFFFFF',
    border: '#252545',
    input: '#252545',
  },
  radius: 14,
};

export default colors;
